<?xml version="1.0" encoding="utf-8"?><Database Name="UniversityDB" Class="UniversityDataDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\UniversityDB.mdf;Integrated Security=True" SettingsObjectName="LINQTOSQL.Properties.Settings" SettingsPropertyName="UniversityDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Student" Member="Students">
    <Type Name="Student">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="S_Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Reg" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Teacher" Member="Teachers">
    <Type Name="Teacher">
      <Column Name="SL" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="T_Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Department" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Dept" Member="Depts">
    <Type Name="Dept">
      <Column Name="Deptno" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Loc" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Dept_Emp" Member="Emps" ThisKey="Deptno" OtherKey="Deptno" Type="Emp" />
    </Type>
  </Table>
  <Table Name="dbo.Emp" Member="Emps">
    <Type Name="Emp">
      <Column Name="Empno" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Ename" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Job" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Mgr" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HireDate" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="Sal" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Comm" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Deptno" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Emp_Emp" Member="Emps" ThisKey="Empno" OtherKey="Mgr" Type="Emp" />
      <Association Name="Dept_Emp" Member="Dept" ThisKey="Deptno" OtherKey="Deptno" Type="Dept" IsForeignKey="true" />
      <Association Name="Emp_Emp" Member="Emp1" ThisKey="Mgr" OtherKey="Empno" Type="Emp" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.Student_Select" Method="Student_Select">
    <ElementType Name="Student_SelectResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="S_Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Reg" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.Student_SpSc" Method="Student_SpSc">
    <Parameter Name="sname" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="Student_SpScResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="S_Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Reg" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.Teacher_Select" Method="Teacher_Select">
    <ElementType Name="Teacher_SelectResult">
      <Column Name="SL" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="T_Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Department" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.Teacher_SpSc" Method="Teacher_SpSc">
    <Parameter Name="tname" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="Teacher_SpScResult">
      <Column Name="SL" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="T_Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Department" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.Teacher_Insert" Method="Teacher_Insert">
    <Parameter Name="tname" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="dname" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="sl" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
</Database>